### PR TITLE
Update the crates.io meeting time.

### PR DESCRIPTION
**Pull request by smarnach**

### CODE REVIEW

**Comment by carols10cents** [comment]
Neither the old nor the new thetimezoneconverter.com links are working for me in Firefox or Chrome; I get `NaN:aN PM GMT` on the left: 

Screen Shot of thetimezoneconverter.com problem

I tried choosing 10:30AM ET to create a new link and I'm not seeing the URL change or a way to share a URL. Is this a personal problem of mine? If not, can we switch to something else?

**Comment by pietroalbini** [comment]
GitHub's diff view is rendering the URLs incorrectly, [but they work in the rendered version](https://github.com/rust-lang/crates-io-cargo-teams/blob/d472fd5754fdeb17341f807fac30afe56d30ddad/README.md#cratesio-team).

**Comment by locks** [comment]
@carols10cents you are missing the closing `)` in the URL, I did the same thing!

**Comment by locks** [comment]
@smarnach Can you confirm that during DST changes the source of truth is ET?

**Comment by smarnach** [comment]
@locks I think we decided sticking with US DST. The exact US timezone doesn't matter too much, since all US mainland timezones with DST change the clocks at the same time, as far as I'm aware. If we choose a different timezone for DST, I'm fine with that, too.

**Comment by locks** [comment]
I'm fine with whatever as well, just wanted to confirm for my calendar reminder :)

**Comment by sgrif** [comment]
Yes, Eastern is the source of truth for DST (If folks have another preference for a time zone to anchor to we can use it, but I think we're better off sticking to some time zone that follows DST as long as the majority of team members follow it)

**Pull request merged**
